import PDFDocument from 'pdfkit';
import { format } from 'date-fns';

export const generatePurchaseOrderPDF = async (po: any): Promise<Buffer> => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];

        doc.on('data', (chunk) => buffers.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', (err) => reject(err));

        // Header
        doc.fillColor('#444444')
            .fontSize(20)
            .text('KK Trendz', 50, 50)
            .fontSize(10)
            .text('123 Textile Avenue, Industrial Area', 400, 50, { align: 'right' })
            .text('Coimbatore, Tamil Nadu - 641001', 400, 65, { align: 'right' })
            .text('Phone: +91 98765 43210', 400, 80, { align: 'right' })
            .moveDown();

        const hr = (y: number) => {
            doc.moveTo(50, y).lineTo(550, y).strokeColor('#eeeeee').stroke();
        };

        hr(100);

        // PO Header Details
        doc.fontSize(16).fillColor('#333333').text('PURCHASE ORDER', 50, 120);

        doc.fontSize(10).fillColor('#666666')
            .text(`PO Number: ${po.poNumber}`, 50, 150)
            .text(`Date: ${format(new Date(po.poDate), 'dd-MMM-yyyy')}`, 50, 165)
            .text(`Expected Delivery: ${po.expectedDelivery ? format(new Date(po.expectedDelivery), 'dd-MMM-yyyy') : 'N/A'}`, 50, 180);

        // Supplier Info
        const supplier = po.supplierId;
        doc.fontSize(12).fillColor('#333333').text('SUPPLIER', 350, 120);
        doc.fontSize(10).fillColor('#666666')
            .text(supplier.partyName, 350, 140)
            .text(supplier.address || '', 350, 155)
            .text(`Contact: ${supplier.primaryContact || ''}`, 350, 170)
            .text(`Email: ${supplier.email || ''}`, 350, 185);

        doc.moveDown(4);

        // Table Header
        const tableTop = 230;
        doc.fontSize(10).fillColor('#ffffff').rect(50, tableTop, 500, 20).fill('#4f46e5');
        doc.fillColor('#ffffff')
            .text('Product Description / Specifications', 60, tableTop + 5)
            .text('Qty', 300, tableTop + 5)
            .text('Rate', 350, tableTop + 5)
            .text('Disc%', 410, tableTop + 5)
            .text('Tax%', 460, tableTop + 5)
            .text('Amount', 510, tableTop + 5);

        // Table Body
        let currentY = tableTop + 25;
        doc.fillColor('#333333');
        po.items.forEach((item: any) => {
            const desc = item.productId?.productName || item.productDescription;
            const specs = item.yarnSpecs ? `${item.yarnSpecs.count} ${item.yarnSpecs.ply} ${item.yarnSpecs.blend} ${item.yarnSpecs.brand}`.trim() : '';

            doc.fontSize(9).text(desc, 60, currentY);
            if (specs) {
                currentY += 12;
                doc.fontSize(8).fillColor('#666666').text(`Specs: ${specs}`, 60, currentY).fillColor('#333333');
            }

            doc.fontSize(9)
                .text(item.orderQuantity.toString(), 300, currentY - (specs ? 12 : 0))
                .text(item.rate.toFixed(2), 350, currentY - (specs ? 12 : 0))
                .text(`${item.discountPercentage}%`, 410, currentY - (specs ? 12 : 0))
                .text(`${item.gstRate}%`, 460, currentY - (specs ? 12 : 0))
                .text(item.totalAmount.toFixed(2), 510, currentY - (specs ? 12 : 0));

            currentY += 20;
            hr(currentY - 5);
        });

        // Totals
        const summary = po.financialSummary;
        currentY += 10;
        doc.fontSize(10).fillColor('#666666')
            .text('Taxable Amount:', 380, currentY)
            .text(summary.taxableTotal.toFixed(2), 500, currentY, { align: 'right' });

        currentY += 15;
        doc.text('GST Total:', 380, currentY)
            .text(summary.gstTotal.toFixed(2), 500, currentY, { align: 'right' });

        currentY += 20;
        doc.fontSize(12).fillColor('#4f46e5').font('Helvetica-Bold')
            .text('GRAND TOTAL:', 380, currentY)
            .text(`INR ${summary.grandTotal.toFixed(2)}`, 450, currentY, { align: 'right' });

        // Footer
        const bottom = 750;
        doc.fontSize(8).fillColor('#999999').font('Helvetica')
            .text('Generated by KK Trendz ERP', 50, bottom, { align: 'center' })
            .text('This is a computer generated document and does not require a physical signature.', 50, bottom + 12, { align: 'center' });

        doc.end();
    });
};

export const generateGrnPDF = async (grn: any): Promise<Buffer> => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];

        doc.on('data', (chunk) => buffers.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', (err) => reject(err));

        // Header
        doc.fillColor('#444444')
            .fontSize(20)
            .text('KK Trendz', 50, 50)
            .fontSize(10)
            .text('123 Textile Avenue, Industrial Area', 400, 50, { align: 'right' })
            .text('Coimbatore, Tamil Nadu - 641001', 400, 65, { align: 'right' })
            .text('Phone: +91 98765 43210', 400, 80, { align: 'right' })
            .moveDown();

        const hr = (y: number) => {
            doc.moveTo(50, y).lineTo(550, y).strokeColor('#eeeeee').stroke();
        };

        hr(100);

        // GRN Header Details
        doc.fontSize(16).fillColor('#333333').text('GOODS RECEIPT NOTE (GRN)', 50, 120);

        doc.fontSize(10).fillColor('#666666')
            .text(`GRN Number: ${grn.grnNumber}`, 50, 150)
            .text(`GRN Date: ${format(new Date(grn.grnDate), 'dd-MMM-yyyy')}`, 50, 165)
            .text(`PO Ref: ${grn.poId?.poNumber || 'Direct Receipt'}`, 50, 180)
            .text(`Challan No: ${grn.challanNo}`, 50, 195);

        // Supplier Info
        const supplier = grn.supplierId;
        doc.fontSize(12).fillColor('#333333').text('SUPPLIER', 350, 120);
        doc.fontSize(10).fillColor('#666666')
            .text(supplier?.partyName || 'N/A', 350, 140)
            .text(supplier?.address || '', 350, 155)
            .text(`Contact: ${supplier?.primaryContact || ''}`, 350, 170);

        doc.moveDown(4);

        // Table Header
        const tableTop = 240;
        doc.fontSize(10).fillColor('#ffffff').rect(50, tableTop, 500, 20).fill('#4f46e5');
        doc.fillColor('#ffffff')
            .text('Product Description', 60, tableTop + 5)
            .text('Received', 250, tableTop + 5)
            .text('Accepted', 320, tableTop + 5)
            .text('Rejected', 390, tableTop + 5)
            .text('Batch/Bin', 460, tableTop + 5);

        // Table Body
        let currentY = tableTop + 25;
        doc.fillColor('#333333');
        grn.items.forEach((item: any) => {
            const desc = item.productId?.productName || item.productDescription;
            const batchInfo = `${item.batchNumber || ''}${item.binNumber ? ' (' + item.binNumber + ')' : ''}`;

            doc.fontSize(9).text(desc, 60, currentY, { width: 180 });
            doc.text(`${item.receivedQuantity} ${item.unit}`, 250, currentY);
            doc.fillColor('#10b981').text(`${item.acceptedQuantity} ${item.unit}`, 320, currentY);
            doc.fillColor(item.rejectedQuantity > 0 ? '#ef4444' : '#333333').text(`${item.rejectedQuantity} ${item.unit}`, 390, currentY);
            doc.fillColor('#666666').text(batchInfo, 460, currentY);
            doc.fillColor('#333333');

            currentY += 25;
            hr(currentY - 5);
        });

        // Totals
        currentY += 10;
        doc.fontSize(10).fillColor('#666666')
            .text('Total Accepted Quantity:', 300, currentY)
            .fontSize(12).fillColor('#10b981').font('Helvetica-Bold')
            .text(`${grn.summary.totalAccepted} ${grn.items[0]?.unit}`, 450, currentY, { align: 'right' });

        if (grn.summary.totalRejected > 0) {
            currentY += 20;
            doc.fontSize(10).fillColor('#666666').font('Helvetica')
                .text('Total Rejected Quantity:', 300, currentY)
                .fillColor('#ef4444').font('Helvetica-Bold')
                .text(`${grn.summary.totalRejected} ${grn.items[0]?.unit}`, 450, currentY, { align: 'right' });
        }

        // Logistics Info
        currentY += 40;
        doc.fontSize(10).fillColor('#333333').font('Helvetica-Bold').text('Logistics & Verification', 50, currentY);
        doc.fontSize(9).fillColor('#666666').font('Helvetica')
            .text(`Vehicle No: ${grn.vehicleNumber || 'Not Recorded'}`, 50, currentY + 15)
            .text(`Received By: ${grn.receivedBy?.name || 'Admin'}`, 50, currentY + 30)
            .text(`Verified By: ${grn.checkedBy?.name || 'Quality Team'}`, 50, currentY + 45);

        // Footer
        const bottom = 750;
        doc.fontSize(8).fillColor('#999999').font('Helvetica')
            .text('Generated by KK Trendz ERP', 50, bottom, { align: 'center' })
            .text('This GRN Slip is computer generated and valid as official receipt record.', 50, bottom + 12, { align: 'center' });

        doc.end();
    });
};

